layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: evan_bradley
  instagram: _evan_bradley
  # keybase: your_username
  linkedin: evan-bradley
  # medium: your_username
  stackoverflow: 11671478
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Data Analysis
    web_url: https://github.com/topics/data-analysis
    image_url: https://tr1.cbsistatic.com/hub/i/r/2015/09/30/f66fef72-5d57-48cc-bd8c-7ec0941e73ef/resize/770x/ac0363c3e414d51bafb1dd9b1c8a604a/dataanalysisistockrobuart.jpg

  - name: Artificial Intelligence
    web_url: http://animalaiolympics.com/
    image_url: https://spectrum.ieee.org/image/MzIzOTE0Ng.jpeg

  - name: Databases
    web_url: https://github.com/topics/database
    image_url: http://blogs.bmc.com/wp-content/uploads/2016/06/database-blue.png
